In [2]:
#1. [簡答題] 請問下列兩種將 Array 轉換成 List 的方式有何不同？
#print('list(a): ', list(a)) => list(a) 只會把第一層的元素轉換成 List，多層的話只有第一層會轉
#print('tolist(): ', a.tolist()) => tolist() 才能達成多層的型態轉換
import numpy as np
a = np.random.randint(10, size=6) 
print('List(a):', list(a))
print('tolist():', a.tolist())

b = np.random.randint(10, size=6).reshape(3, 2) 
print('List(b):', list(b))
print('tolist():', b.tolist())


List(a): [9, 7, 2, 8, 9, 7]
tolist(): [9, 7, 2, 8, 9, 7]
List(b): [array([8, 6]), array([4, 4]), array([6, 6])]
tolist(): [[8, 6], [4, 4], [6, 6]]


In [12]:
#2. 請試著在程式中印出以下三個 NdArray 的屬性並且解釋結果？（屬性：ndim、shape、size、dtype、itemsize、length、type）
import numpy as np
a = np.random.randint(10, size=6) 
print(a)
print(a.ndim) #陣列有多少維度
print(a.shape) #每個維度的大小
print(a.size) #陣列當中有幾個元素
print(a.dtype) #陣列中的資料型態
print(a.itemsize) #陣列中每個元素佔用的空間
print(len(a)) #陣列的長度
print(type(a)) #陣列的類型

[7 8 9 1 9 8]
1
(6,)
6
int32
4
6
<class 'numpy.ndarray'>


In [13]:
b = np.random.randint(10, size=(3,4)) 

print(b)
print(b.ndim) #陣列有多少維度
print(b.shape) #每個維度的大小
print(b.size) #陣列當中有幾個元素
print(b.dtype) #陣列中的資料型態
print(b.itemsize) #陣列中每個元素佔用的空間
print(len(b)) #陣列的長度
print(type(b)) #陣列的類型

[[1 2 6 5]
 [0 8 8 4]
 [8 2 9 5]]
2
(3, 4)
12
int32
4
3
<class 'numpy.ndarray'>


In [14]:
c = np.random.randint(10, size=(2,3,2))

print(c)
print(c.ndim) #陣列有多少維度
print(c.shape) #每個維度的大小
print(c.size) #陣列當中有幾個元素
print(c.dtype) #陣列中的資料型態
print(c.itemsize) #陣列中每個元素佔用的空間
print(len(c)) #陣列的長度
print(type(c)) #陣列的類型

[[[8 8]
  [9 3]
  [2 2]]

 [[8 3]
  [9 5]
  [5 5]]]
3
(2, 3, 2)
12
int32
4
2
<class 'numpy.ndarray'>


In [15]:
# 3. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。
a = np.random.randint(10, size=6) 

print(a.tolist())
print(list(a))


[2, 6, 8, 9, 6, 2]
[2, 6, 8, 9, 6, 2]


In [16]:
b = np.random.randint(10, size=(3,4)) 

print(b.tolist())
print(list(b))

[[9, 9, 1, 4], [1, 8, 3, 4], [7, 2, 3, 3]]
[array([9, 9, 1, 4]), array([1, 8, 3, 4]), array([7, 2, 3, 3])]


In [5]:
c = np.random.randint(10, size=(2,3,2))

print(c.tolist())
print(list(c))

[[[8, 7], [8, 5], [3, 3]], [[6, 5], [8, 8], [1, 8]]]
[array([[8, 7],
       [8, 5],
       [3, 3]]), array([[6, 5],
       [8, 8],
       [1, 8]])]


In [7]:
#way1
def tolist(iterable):
    if type(iterable) != np.ndarray:
        return iterable
    newlist = []
    for obj in iterable:
        newlist.append(tolist(obj))
    return list(newlist)
print(tolist(a))
print(tolist(b))
print(tolist(c))

#way2
def tolist(iterable):
    if type(iterable) != np.ndarray:
        return iterable
    return [tolist(obj) for obj in iterable]

print(tolist(a))
print(tolist(b))
print(tolist(c))

[9, 7, 2, 8, 9, 7]
[[8, 6], [4, 4], [6, 6]]
[[[8, 7], [8, 5], [3, 3]], [[6, 5], [8, 8], [1, 8]]]
[9, 7, 2, 8, 9, 7]
[[8, 6], [4, 4], [6, 6]]
[[[8, 7], [8, 5], [3, 3]], [[6, 5], [8, 8], [1, 8]]]
