In [ ]:
# 1. [簡答題] 請比較 np.zeros 和 np.empty 產生出來的陣列有何差異？為什麼要設計兩種方法？
#zeros產生的陣列都是由0組成
#empty產生的陣列是接近0的數字
#np.empty可以用於只是想要初始化,之後就會覆寫數值的狀況

In [13]:
# 2.在不用「整數亂數方法」的限制下，如何將包含小數的轉換整數？請將給定的 a 陣列當中的元素變成去掉小數變成整數。
import numpy as np
a = np.random.rand(2, 3)
a = a * 100
print(a.round())
#print(np.round(a))

[[78. 38.  8.]
 [46. 92. 65.]]


In [15]:
# 3.承上題，怎樣可以限制整數的範圍介於 m - n 之間？請將給定的 a 陣列當中的元素的範圍調整成 m - n 之間。
m = 20
n = 40
a = np.random.rand(2, 3)*(n - m)
b = a 
print(a)
print((b - a % 1) + m)


[[17.61111565  8.85276141  7.18881084]
 [ 0.18282558 15.2740277  18.77866812]]
[[37. 28. 27.]
 [20. 35. 38.]]
