In [1]:
#1. [簡答題] 請問下列程式碼，運算結果分別為何？
import numpy as np

a = np.array( [20,30,40,50] )
b = np.array( [1,2,3,4] ) 
c = 1
d = np.array( [1] )
e = np.array( [1,2] ) 

print(a + a)
print(a + b)
print(a + c)
print(a + d)
print(a + e)


[ 40  60  80 100]
[21 32 43 54]
[21 31 41 51]
[21 31 41 51]


ValueError: operands could not be broadcast together with shapes (4,) (2,) 

In [7]:
#2. 如何在不用迴圈的情況下計算 (A+B)*(-A/2) ？那用迴圈怎麼做？
import numpy as np
a = np.array( [20,30,40,50] )
b = np.array( [1,2,3,4] ) 
print((a + b) * (- a /2))

a = [20,30,40,50]
b = []
j = 0

for i in a:
    j += 1
    b.append((i + j) * (-i / 2))
print(b)
    

[ -210.  -480.  -860. -1350.]
[-210.0, -480.0, -860.0, -1350.0]


In [11]:
#3. 請問如何計算「1x6 的單位矩陣」和「6x1 的單位矩陣」的內積和外積？
import numpy as np

a = np.ones((1, 6))
b = np.ones((6, 1))

print(a * b)
print(a @ b)

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]
[[6.]]
