In [10]:
#1. 產生一個 1-11 的一維陣列，並且把 3-6 由正數變成負數。
import numpy as np
a = np.arange(1,12)

a[(a > 2) & (a < 7)] *= -1

print(a)


[ 1  2 -3 -4 -5 -6  7  8  9 10 11]


In [16]:
#2. 試著從一個隨機陣列中，找出比 0.5 大的數有幾個？
import numpy as np
a = np.random.rand(2, 3)
print(a)
print(a[a > 0.5])
print(a[a > 0.5].size)

[[0.10148675 0.01077425 0.64223367]
 [0.77512865 0.32231552 0.85682518]]
[0.64223367 0.77512865 0.85682518]
3
