In [3]:
#[簡答題] 請問下列這三種方法有什麼不同？
import numpy as np

a = np.arange(6)

print(a.sum())
print(np.sum(a))
print(sum(a)) 
#a.sum() & np.sum(a)是Numpy裡的函式 sum(a)是python裡的函式

15
15
15


In [21]:
#請對一個 5x5 的隨機矩陣作正規化的操作。(全部轉換成0~1之間)
import numpy as np
b = np.random.random((5, 5))
print(b)
b = (b - b.min()) / (b.max() - b.min())
print(b)


[[0.42676494 0.15125641 0.87864881 0.12012535 0.77952541]
 [0.65652726 0.12509642 0.46923471 0.20622638 0.18771002]
 [0.13316005 0.0235152  0.71867091 0.97197496 0.10330662]
 [0.9904535  0.11660322 0.74749298 0.54781415 0.82658056]
 [0.65226171 0.47790225 0.15433514 0.70974202 0.36168154]]
[[0.41703771 0.13210895 0.88437246 0.09991346 0.78185982]
 [0.6546561  0.10505449 0.46095961 0.18895847 0.169809  ]
 [0.11339384 0.         0.71892457 0.98088963 0.08251966]
 [1.         0.0962709  0.74873213 0.54222585 0.83052389]
 [0.6502447  0.46992352 0.13529295 0.70969039 0.34972898]]


In [27]:
#請建立一個長度等於 10 的正整數向量，並且將其中的最大值改成 -1。
import numpy as np
c = np.random.randint(100, size = 10)
print(c)
c[c.argmax()] = -1
print(c)

[ 5 69 86 91 48 55 35  1 57 70]
[ 5 69 86 -1 48 55 35  1 57 70]
